#!/bin/bash

#created June 2018 (Catherine Cunningham). Edited by Michael Freedberg on September 2nd, 2019.

#run this script after tort_QC
#creates glyph maps via tortoise command for QC assessment
#requires nifti files generated by EstimateTensorWLLS
#requires user to enter bash shell prior to running script
#WARNING: THIS SCRIPT ONLY WORKS WHEN RUN LOCALLY
################# Input Variable ################
### Enter base path (where DTI_Analyses is).
home_dir=ENTER PATH!!!!
### Set Subject
subj=S01
### Set path to Subjects_QC folder
InDrive=ENTER PATH!!!
########################

for subj in S01
    do
    ########################
    #set paths for imported AP and PA data
    path_AP=$InDrive/$subj/dti_ap_proc
    path_PA=$InDrive/$subj/dti_pa_proc
    echo
    echo ////// computing glyph maps for $subj //////
    echo
    #ap
    ComputeGlyphMaps $path_AP/dti_ap_L0_DT.nii axial
    ComputeGlyphMaps $path_AP/dti_ap_L0_DT.nii sagittal
    ComputeGlyphMaps $path_AP/dti_ap_L0_DT.nii coronal
    #pa
    ComputeGlyphMaps $path_PA/dti_pa_L0_DT.nii axial
    ComputeGlyphMaps $path_PA/dti_pa_L0_DT.nii sagittal
    ComputeGlyphMaps $path_PA/dti_pa_L0_DT.nii coronal
done #subj
